name = "PackageReleaseTest"
uuid = "3fac36aa-54f2-405c-a981-23ff7c8a7917"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.1.0"

[compat]
GeometricObjects = "0.3"
Poingr = "0.10"
StructArrays = "0.6"
julia = "1.6"
